# -*- coding: utf-8 -*-
"""AIML-Lab-1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BL_-2uv-dL6qbLkRwlpNiW-0LMBnWrD7
"""

import pandas as pd
import matplotlib.pyplot as plt
csv = pd.read_csv('/content/sample_data/california_housing_train.csv')

csv

print("Size = ",csv.size)
print("Shape = ",csv.shape)
print("Dimensions = ",csv.ndim)

x = csv["population"]
y = csv["households"]
plt.plot (x,y)

plt.bar (x,y,width=0.1)

